source 'http://rubygems.org'

gem 'sinatra'
gem 'compass'
gem 'bson'
gem 'bson_ext'
gem 'mongoid'
gem 'openid_mongodb_store'
gem 'bcrypt-ruby'
gem 'ruby-openid', :git => 'git://github.com/mbleigh/ruby-openid.git'

gem 'omniauth',          '~> 1.0.0.rc2'
gem 'omniauth-github',   '~> 1.0.0.rc2', :git => 'git://github.com/intridea/omniauth-github.git'
gem 'omniauth-openid',   '~> 1.0.0.rc2'
gem 'omniauth-contrib',  '~> 1.0.0.rc2', :git => 'git://github.com/intridea/omniauth-contrib.git'
gem 'omniauth-facebook', :git => 'git://github.com/mkdynamic/omniauth-facebook.git'
gem 'omniauth-linkedin', :git => 'git://github.com/mbleigh/omniauth-linkedin.git', :branch => 'patch-1'
gem 'omniauth-identity', :git => 'git://github.com/intridea/omniauth-identity.git'
