source 'http://rubygems.org'

gem 'sinatra'
gem 'compass'
gem 'mongo', '1.3.1'
gem 'bson_ext', '1.3.1'
gem 'mongoid', '2.2.3'
gem 'openid_mongodb_store'
gem 'bcrypt-ruby'
gem 'ruby-openid', :git => 'git://github.com/mbleigh/ruby-openid.git'

gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-openid'
gem 'omniauth-identity'
gem 'omniauth-contrib',  :git => 'git://github.com/intridea/omniauth-contrib.git'
gem 'omniauth-facebook', :git => 'git://github.com/mkdynamic/omniauth-facebook.git'
gem 'omniauth-linkedin', :git => 'git://github.com/mbleigh/omniauth-linkedin.git', :branch => 'patch-1'
gem 'omniauth-geoloqi'